name: 04 - Using Actions

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-Using-actions/react-app/
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name:  Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Debug - list current directory
              run:  ls -R
            - name: Install Dependecies
              run: npm ci
            #   working-directory: 04-Using-actions/react-app/
            - name: Run unit test
              run:  npm run test



        # 0.Checkout code from the repository