name: 05 - 1 - Event Filters and Activity types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
              - run: |
                    echo "Runnning whenever a PR is opened or synchronized AND base branch is main"
                    echo "i have trigerred by {{ github.event_name }}"
                    echo "The RUNNER OS is $RUNNER_OS"

