name: 06 - Contexts
run-name: 06 - Contexts | DEBUG ${{ inputs.debug }}

on:
    push:
    workflow_dispatch:
      inputs:
        DEV:
          type: boolean
          default: false

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
          MY_JOB_VAR: 'job'
          MY_OVERWRITTEN_VAR: 'job'
        steps:
            - name: Display Information
              run: |
                echo "Event Name: ${{ github.event_name }}"
                echo "Ref: ${{ github.base_ref }}"
                echo "SHA ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run Number: ${{ github.run_number }}"
            - name: Retrive Variable
              run: |
                echo "Variable Value: ${{ vars.MY_VAR }}"
            - name: Print Env Variables
              env:
                MY_OVEWRITTEN_VAR: 'step'
              run: |
                echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                echo  "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
            - name: Print Env Variables
              run: |
                  echo "Workflow env: ${{ env.MY_WORKFLOW_VAR }}"
                  echo  "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR }}"
    echo-data2:
      runs-on: ubuntu-latest
      steps:
        - name: Print Env Variables
          run: |
              echo "Workflow env: $MY_WORKFLOW_VAR"
              echo  "Overwritten env: $MY_OVERWRITTEN_VAR"


