name:   09 - Using functions

on:
    workflow_dispatch:
    pull_request:

jobs:
    echo1:
        runs-on: ubuntu-latest

        steps:

            - name: informations
              run: |
                echo "I have triggered by ${{ github.event_name }}}"
                echo "Run By: ${{ github.actor }}"
                echo "Running On: ${{ runner.name }} and ${{ runner.os }}"
                echo "${{ github.workflow }} "

            - name: Failing step
              run: sleep 10

            - name: Failing step
              run: exit 1

            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous step is succeed."

            - name: I will execute
              if: ${{ failure() }}
              run: echo "I will print if any previous step fails."

            - name: i will execute when cancelled
              if: ${{ !cancelled() }}
              run: echo "I will alway print, except workflow is cancelled. "

            - name: I will execute when cancelled
              if: ${{ cancelled() }}
              run: echo "I will print, if the workflow has been cancelled."

            

            
