name: 11 Working With Inputs

on:
    workflow_dispatch:
        inputs:
            dry-run:
                type: boolean
                description: Skip deployment and only print build output
                default: false
            
            target:
                type: environment
                required: true
                description: Which Enviroment the workflow will target

            tag:
                type: choice
                options:
                    - V1
                    - V2
                    - V3
                default: V3
                description: which enviroment the workflow will target





jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: |
                echo "Building from tag: ${{ inputs.tag }}"
 

    deploy:
        runs-on: ubuntu-latest
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target }}
        needs: build
        steps:
            - name: Deploy
              run: |
                echo "Deploying to ${{ inputs.target }}"