name: 13 - Caching
on:
    workflow_dispatch:
        inputs:
            user-cache:
                description: Whether to execute cache step
                type: boolean
                default: true
            node-version:
                description: Please select an Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                    - 22.x
                default: 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .github/workflows/13-Caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: ${{ inputs.node-version }}

            - name: install dependecies
              run: npm ci
            #   working-directory: 13-Caching/react-app
            - name: testing
              run: npm run test
            #   working-directory: 13-Caching/react-app
            - name: building
              run: npm run build
            - name: deploying to non prod
              run: echo "Deployinmg to non prod"  


        # 1. Checkout the code
        # 2. Install dependecies
        # 3. unit testing, building
        # 4. Deploy to non prod enviroment.
