name: 16 - Working with enviroments

on:
    workflow_dispatch:
           
jobs:
    deploy-staging:
        runs-on: ubuntu-latest
        environment: Staging
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "Deploying to ${{ inputs.target-env }}"

    e2e-tests:
        runs-on: ubuntu-latest
        needs: deploy-staging
        steps:
            - name: E2E tests
              run: echo "Running E2E"

    echo-prod:
        runs-on: ubuntu-latest
        needs: e2e-tests
        environment: PROD
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
        steps:
            - name: Echo Vars
              run: |
                echo "Deploying to PROD"
        
        