name: 18.1 - Reusable Workflow - Reusable Definition
run-name: Workflow ${{ github.Workflow }} is triggered by ${{ github.actor }}
on:
  Workflow_call:
    inputs:
      target-directory:
        required: true
        type: string
    outputs:
      build-status:
        description: The status of the build process
        value: ${{ jobs.deploy.outputs.build-status }}
      url:
        description: The URL of the depoyed version
        value: ${{ jobs.deploy.outputs.url }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.build-status }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build
        id: build
        run:|
          echo "Building using directory ${{inputs.target-directory}}"
          echo "build-status=success" >> "$GITHUB_OUTPUT"
      - name: deploy
        id: deploy
        run: |
          echo "Deploying build artiffacts"
          echo "url=https//www.google.com" >> "$GITHUB_OUTPUT"