name: Deploy to server
on:
    push:
      branches:
          - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.DEPLOY_SERVERS }}" > /.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa



            - name: Loop and Deploy
              run: |
                
                IFS=',' read -ra HOSTS <<< "${{ secrets.DEPLOY_SERVERS }}"
                for HOST in "${HOSTS[@]}"; do
                  # touch ~/.ssh/known_hosts
                  echo "Deploying to $HOST"
                  ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
                  ssh "$HOST" "echo Connected to $HOST from GitHub Actions"
                done