name: Deploy to server
on:
    push:
      branches:
          - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Loop and Deploy
              run: |
                IFS=',' read -ra HOSTS <<< "${{ secrets.DEPLOY_SERVERS }}
                for HOST in ${HOSTS[@]}"; do
                echo "Deploying to $HOST"
                ssh-keyscan -H "$HOST" >> ~/.ssh/known-hosts
                ssh "$HOST" 'echo Connected to $HOST from GitHub Actions'